---@type table<string, string>
local M = {
  BarbecueMod = "BufferVisibleMod",
  BarbecueEllipsis = "Conceal",
  NavicText = "Normal",
  NavicSeparator = "Conceal",
  NavicIconsFile = "CmpItemKindFile",
  NavicIconsPackage = "CmpItemKindFolder",
  NavicIconsModule = "CmpItemKindModule",
  NavicIconsNamespace = "CmpItemKindModule",
  NavicIconsClass = "CmpItemKindClass",
  NavicIconsConstructor = "CmpItemKindConstructor",
  NavicIconsField = "CmpItemKindField",
  NavicIconsProperty = "CmpItemKindProperty",
  NavicIconsMethod = "CmpItemKindMethod",
  NavicIconsStruct = "CmpItemKindStruct",
  NavicIconsEvent = "CmpItemKindEvent",
  NavicIconsInterface = "CmpItemKindInterface",
  NavicIconsEnum = "CmpItemKindEnum",
  NavicIconsEnumMember = "CmpItemKindEnumMember",
  NavicIconsConstant = "CmpItemKindConstant",
  NavicIconsFunction = "CmpItemKindFunction",
  NavicIconsTypeParameter = "CmpItemKindTypeParameter",
  NavicIconsVariable = "CmpItemKindVariable",
  NavicIconsOperator = "CmpItemKindOperator",
  NavicIconsNull = "CmpItemKindValue",
  NavicIconsBoolean = "CmpItemKindValue",
  NavicIconsNumber = "CmpItemKindValue",
  NavicIconsString = "CmpItemKindValue",
  NavicIconsKey = "CmpItemKindValue",
  NavicIconsArray = "CmpItemKindValue",
  NavicIconsObject = "CmpItemKindValue",
}

return M
