---@type table<string, string>
local M = {
  BarbecueNormal = "WinBar",
  BarbecueModified = "BufferVisibleMod",
  BarbecueEllipsis = "Conceal",
  BarbecueSeparator = "Conceal",
  BarbecueDirname = "Normal",
  BarbecueBasename = "Normal",
  BarbecueContext = "Normal",
  BarbecueContextFile = "CmpItemKindFile",
  BarbecueContextModule = "CmpItemKindModule",
  BarbecueContextNamespace = "CmpItemKindModule",
  BarbecueContextPackage = "CmpItemKindFolder",
  BarbecueContextClass = "CmpItemKindClass",
  BarbecueContextMethod = "CmpItemKindMethod",
  BarbecueContextProperty = "CmpItemKindProperty",
  BarbecueContextField = "CmpItemKindField",
  BarbecueContextConstructor = "CmpItemKindConstructor",
  BarbecueContextEnum = "CmpItemKindEnum",
  BarbecueContextInterface = "CmpItemKindInterface",
  BarbecueContextFunction = "CmpItemKindFunction",
  BarbecueContextVariable = "CmpItemKindVariable",
  BarbecueContextConstant = "CmpItemKindConstant",
  BarbecueContextString = "CmpItemKindValue",
  BarbecueContextNumber = "CmpItemKindValue",
  BarbecueContextBoolean = "CmpItemKindValue",
  BarbecueContextArray = "CmpItemKindValue",
  BarbecueContextObject = "CmpItemKindValue",
  BarbecueContextKey = "CmpItemKindValue",
  BarbecueContextNull = "CmpItemKindValue",
  BarbecueContextEnumMember = "CmpItemKindEnumMember",
  BarbecueContextStruct = "CmpItemKindStruct",
  BarbecueContextEvent = "CmpItemKindEvent",
  BarbecueContextOperator = "CmpItemKindOperator",
  BarbecueContextTypeParameter = "CmpItemKindTypeParameter",
}

return M
